language: python
install:
- pip install -r requirements.txt
- python setup.py install
script:
- pytest
deploy:
  skip_cleanup: true
  provider: pypi
  user: tpoveda
  password:
    secure: PN+D65bZs6TKDsCoe4n1+2CV/60787L/C1/4D4Z/TcO4RoUbM8e4/nUbTFRoglEZ46xjtu4NuDZltmKMABwYYVHCYGiIZGLvRL+Qn33oI7OMVSFeXFkCTPZI+sGJk6QX17A0HolSoEPWkMbvWIMKHI2WQqfErdk6H0HWSMOxYtj1ar4XGbUdUCAcGaZJe50L0RZmC7/tto6XdhSP666YQwhmUQ2qB3+cMZF+wultu/xPkJa3oTDLfGDUuqLpJ9x9J7ma/4okis39wlnBr2hpcfpa0XjxXUVgcsSZNAC1duptefZmeMLfzRKSb4sQVtKDZev75c/iEg8lR1mOacHwfGC512Xaj1ZIXBTVKXA3Rb9XSvl806whdAaLp/JpfhtlfP7GeVsZul/Arh0by9jQtK1F3/ZI/V4O3dWd8Mj9tTqO3tQwod1U3ZXwkhFls78/EjxgAKxfzgghHjK5WlEwfSWDGHpOrWNuxp9v1xAFtejWo9A/uGYwYK7DkCD0IKfiZvWiBntO9Xc6Ckky8qf0Uv9LjJZmedM1XvEuqfF2x/DSAovaLRCIzn0E7zqe8Aip6o1lxBKZX1xCZ5uaw+VeqBy00hJTaGq0Q0WSDAqJeAzNxa/qQRU6VICBo/PxohLViJ6zn+Vy3UqvLU+PuuQ9Yg8kqKOXX0LOTBtxdWtgek4=
  on:
    branch: master
    tags: true